#Transfer XML to Data Frame

In [1]:
from google.colab import files

uploaded = files.upload()

Saving transport44.xml to transport44.xml

In [2]:
from xml.etree.ElementTree import parse

In [3]:
doc = parse('transport44.xml')

In [4]:
print(doc)

<xml.etree.ElementTree.ElementTree object at 0x7f0db9ba95f8>

In [5]:
print(dir(doc))

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_root', '_setroot', 'find', 'findall', 'findtext', 'getiterator', 'getroot', 'iter', 'iterfind', 'parse', 'write', 'write_c14n']

In [ ]:
for item in doc.iterfind('ServiceDelivery'):
  for item2 in item.iterfind('StopMonitoringDelivery'):

    print(item2.findtext('ResponseTimestamp'))
    print(item2.findtext('Status'))
    print(item.findtext('ResponseTimestamp'))

In [ ]:
import pandas as pd

#rows and column for MonitoredStopVisit object
colsMonitoredStopVisit = ['RecordedAtTime', 'ItemIdentifier', 'MonitoringRef']
rowsMonitoredStopVisit = []

#rows and column for MonitoredVehicleJourney object
colsMonitoredVehicleJourney = ['LineRef', 'DirectionRef', 'PublishedLineName','OperatorRef','DestinationRef','OriginAimedDepartureTime',
                               'Bearing','Velocity','VehicleRef']
rowsMonitoredVehicleJourney = []

#rows and column for VehicleLocation object
colsVehicleLocation = ['Longitude', 'Latitude']
rowsVehicleLocation = []

#rows and column for MonitoredCall object
colsMonitoredCall = ['StopPointRef', 'Order','ExpectedArrivalTime','DistanceFromStop']
rowsMonitoredCall = []

for document in doc.iterfind('ServiceDelivery'):
  for item in document.iterfind('StopMonitoringDelivery'):
    print(item.findtext('ResponseTimestamp'))
    print(item.findtext('Status'))
    for item2 in item.iterfind('MonitoredStopVisit'):
      rowsMonitoredStopVisit.append({
                  'RecordedAtTime': item2.findtext('RecordedAtTime'), 
                  'ItemIdentifier': item2.findtext('ItemIdentifier'),
                  'MonitoringRef':item2.findtext('MonitoringRef')})
      dfMonitoredStopVisit = pd.DataFrame(rowsMonitoredStopVisit, columns = colsMonitoredStopVisit) 

      for item3 in item2.iterfind('MonitoredVehicleJourney'):
        rowsMonitoredVehicleJourney.append({
                  'LineRef': item3.findtext('LineRef'), 
                  'DirectionRef': item3.findtext('DirectionRef'),
                  'PublishedLineName':item3.findtext('PublishedLineName'),
                  'OperatorRef':item3.findtext('OperatorRef'),
                  'DestinationRef':item3.findtext('DestinationRef'),
                  'OriginAimedDepartureTime':item3.findtext('OriginAimedDepartureTime'),
                  'Bearing':item3.findtext('Bearing'),
                  'Velocity':item3.findtext('Velocity'),
                  'VehicleRef':item3.findtext('VehicleRef')})      
        dfMonitoredVehicleJourney = pd.DataFrame(rowsMonitoredVehicleJourney, columns = colsMonitoredVehicleJourney) 

        for item4 in item3.iterfind('VehicleLocation'):
          rowsVehicleLocation.append({
                  'Longitude': item4.findtext('Longitude'), 
                  'Latitude': item4.findtext('Latitude')})      
          dfrowsVehicleLocation = pd.DataFrame(rowsVehicleLocation, columns = colsVehicleLocation)
         
        for item5 in item3.iterfind('MonitoredCall'):
          rowsMonitoredCall.append({
                  'StopPointRef': item5.findtext('StopPointRef'), 
                  'Order': item5.findtext('Order'),
                  'ExpectedArrivalTime':item5.findtext('ExpectedArrivalTime'),
                  'DistanceFromStop':item5.findtext('DistanceFromStop')})      
          dfMonitoredCall = pd.DataFrame(rowsMonitoredCall, columns = colsMonitoredCall)

In [ ]:
import pandas as pd
i=1
#all cols and rows
colsAll = ['RecordedAtTime', 'ItemIdentifier', 'MonitoringRef','LineRef', 'DirectionRef', 'PublishedLineName','OperatorRef','DestinationRef','OriginAimedDepartureTime',
                               'Bearing','Velocity','VehicleRef','Latitude','Longitude','StopPointRef', 'Order','ExpectedArrivalTime','DistanceFromStop']
rowsAll = []

for document in doc.iterfind('ServiceDelivery'):
  for item in document.iterfind('StopMonitoringDelivery'):
    print(item.findtext('ResponseTimestamp'))
    print(item.findtext('Status'))
    for item2 in item.iterfind('MonitoredStopVisit'):
      for item3 in item2.iterfind('MonitoredVehicleJourney'):   
        for item4 in item3.iterfind('VehicleLocation'):
          print(i)
          i = i+1
          for item5 in item3.iterfind('MonitoredCall'):
            rowsAll.append({
                    'RecordedAtTime': item2.findtext('RecordedAtTime'), 
                    'ItemIdentifier': item2.findtext('ItemIdentifier'),
                    'MonitoringRef':item2.findtext('MonitoringRef'),
                    'LineRef': item3.findtext('LineRef'), 
                    'DirectionRef': item3.findtext('DirectionRef'),
                    'PublishedLineName':item3.findtext('PublishedLineName'),
                    'OperatorRef':item3.findtext('OperatorRef'),
                    'DestinationRef':item3.findtext('DestinationRef'),
                    'OriginAimedDepartureTime':item3.findtext('OriginAimedDepartureTime'),
                    'Bearing':item3.findtext('Bearing'),
                    'Velocity':item3.findtext('Velocity'),
                    'VehicleRef':item3.findtext('VehicleRef'),
                    'Longitude': item4.findtext('Longitude'), 
                    'Latitude': item4.findtext('Latitude'),
                    'StopPointRef': item5.findtext('StopPointRef'), 
                    'Order': item5.findtext('Order'),
                    'ExpectedArrivalTime':item5.findtext('ExpectedArrivalTime'),
                    'DistanceFromStop':item5.findtext('DistanceFromStop')})      
            dfMonitoredCall = pd.DataFrame(rowsMonitoredCall, columns = colsMonitoredCall) 
            dfAll = pd.DataFrame(rowsAll, columns = colsAll)

In [9]:
dfAll

                RecordedAtTime  ... DistanceFromStop
0    2021-01-11T18:10:45+02:00  ...                0
1    2021-01-11T18:10:01+02:00  ...                0
2    2021-01-11T18:10:43+02:00  ...                0
3    2021-01-11T18:10:01+02:00  ...                0
4    2021-01-11T18:10:16+02:00  ...                0
..                         ...  ...              ...
790  2021-01-11T18:10:37+02:00  ...             3914
791  2021-01-11T18:10:19+02:00  ...             6959
792  2021-01-11T18:09:15+02:00  ...             5573
793  2021-01-11T18:10:44+02:00  ...                0
794  2021-01-11T18:10:42+02:00  ...            18686

[795 rows x 18 columns]

In [12]:
dfAll.loc[dfAll['VehicleRef'] == '7624969']

                RecordedAtTime  ... DistanceFromStop
2    2021-01-11T18:10:43+02:00  ...                0
9    2021-01-11T18:10:43+02:00  ...                0
16   2021-01-11T18:10:43+02:00  ...                0
21   2021-01-11T18:10:43+02:00  ...                0
24   2021-01-11T18:10:43+02:00  ...                0
27   2021-01-11T18:10:43+02:00  ...                0
30   2021-01-11T18:10:43+02:00  ...                0
34   2021-01-11T18:10:43+02:00  ...                0
39   2021-01-11T18:10:43+02:00  ...                0
42   2021-01-11T18:10:43+02:00  ...                0
46   2021-01-11T18:10:43+02:00  ...                0
51   2021-01-11T18:10:43+02:00  ...                0
54   2021-01-11T18:10:43+02:00  ...                0
58   2021-01-11T18:10:43+02:00  ...                0
63   2021-01-11T18:10:43+02:00  ...                0
68   2021-01-11T18:10:43+02:00  ...                0
70   2021-01-11T18:10:43+02:00  ...                0
73   2021-01-11T18:10:43+02:00  ...                0
76   2021-01-11T18:10:43+02:00  ...                0
79   2021-01-11T18:10:43+02:00  ...                0
82   2021-01-11T18:10:43+02:00  ...                0
85   2021-01-11T18:10:43+02:00  ...                0
89   2021-01-11T18:10:43+02:00  ...                0
93   2021-01-11T18:10:43+02:00  ...                0
97   2021-01-11T18:10:43+02:00  ...                0
101  2021-01-11T18:10:43+02:00  ...                0
105  2021-01-11T18:10:43+02:00  ...                0

[27 rows x 18 columns]

In [ ]:
dfAll.dropna(subset=['ExpectedArrivalTime'], inplace=True)
dfAll.reset_index(drop=True,inplace = True)
dfAll

In [ ]:
dfMonitoredStopVisit

In [ ]:
dfMonitoredVehicleJourney

In [ ]:
dfrowsVehicleLocation

In [ ]:
dfMonitoredCall

#Secure code, take data directly from WEB Site (IP Static)

In [ ]:
pip install "requests[security]"

In [ ]:
import csv 
import time as t
import requests 
import xml.etree.ElementTree as ET 
cnt = 1

while True:

  t.sleep(10)
  url = 'https://ims.data.gov.il/sites/default/files/observ.xml'
  
# creating HTTP response object from given url 
  resp = requests.get(url)

# saving the xml file 
  with open('topnewsfeed'+str(cnt)+'.xml', 'wb') as f: 
    cnt = cnt + 1
    f.write(resp.content)
  print(cnt)

#Waze Lib

In [ ]:
pip install WazeRouteCalculator

In [2]:
import WazeRouteCalculator as waze
from google.colab import files
import pandas as pd
uploaded = files.upload()

Saving 921_Bus_Way.xlsx to 921_Bus_Way.xlsx

In [3]:
import pandas as pd
df = pd.read_excel ('921_Bus_Way.xlsx')
print (df)

    Station      Time  Dist        Lat        Lon
0     42658  07:00:00   0.0  32.793372  34.958985
1     42362  07:02:00   1.3  32.789609  34.962117
2     40964  07:03:00   1.9  32.784590  34.962626
3     40958  07:04:00   2.2  32.781207  34.962876
4     40897  07:06:00   3.2  32.772031  34.962995
..      ...       ...   ...        ...        ...
78    23034  09:49:00  90.7  32.083677  34.806421
79    21705  09:51:00  91.9  32.079838  34.794882
80    21472  09:53:00  92.6  32.074914  34.790734
81    28660  09:56:00  94.3  32.061230  34.784594
82    23013  09:58:00  95.2  32.055636  34.780466

[83 rows x 5 columns]

In [4]:
import WazeRouteCalculator
import logging
import time
Lat = df.loc[:,'Lat']
Lon = df.loc[:,'Lon']
n = len(Lat)-1
count = 0
numT = 0

logger = logging.getLogger('WazeRouteCalculator.WazeRouteCalculator')
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
logger.addHandler(handler)

In [5]:
def FullWayBus(From_Lat, To_Lat):
  #logger = logging.getLogger('WazeRouteCalculator.WazeRouteCalculator')
  #logger.setLevel(logging.DEBUG)
  #handler = logging.StreamHandler()
  #logger.addHandler(handler)

  from_address = From_Lat
  to_address = To_Lat
  region = 'IL'
  route = WazeRouteCalculator.WazeRouteCalculator(from_address, to_address, region)
  time = route.calc_route_info()
  return time[0]

In [50]:
#Converting decimal time to original time
def ConvertToOrig(count):
  hours = count // 3600
  minutes = count // 60 - hours * 60

  lent = "%d:%02d" % (hours, minutes)
  print(lent)

In [ ]:
for k in range(0, 8):
  df['i'+str(k)] = 0
  for i in range(0, n):
    st = str(Lat[i])+','+str(Lon[i])
    st2 = str(Lat[i+1])+','+str(Lon[i+1])
    numT = FullWayBus(st, st2)
    count = count + ((int(numT)*60)+(numT*60)%60)
    print(i)
    print((int(numT)*60)+(numT*60)%60)
    df['i'+str(k)][i+1] = (int(numT)*60)+(numT*60)%60
    time.sleep(5)
print(ConvertToOrig(count))

In [8]:
# add new columns to df
#df['i'+str(1)] = None
#df['i'+str(1)][0] = 0
df

    Station      Time  Dist        Lat        Lon   i0
0     42658  07:00:00   0.0  32.793372  34.958985    0
1     42362  07:02:00   1.3  32.789609  34.962117  124
2     40964  07:03:00   1.9  32.784590  34.962626   60
3     40958  07:04:00   2.2  32.781207  34.962876   19
4     40897  07:06:00   3.2  32.772031  34.962995  124
..      ...       ...   ...        ...        ...  ...
78    23034  09:49:00  90.7  32.083677  34.806421   72
79    21705  09:51:00  91.9  32.079838  34.794882  268
80    21472  09:53:00  92.6  32.074914  34.790734   79
81    28660  09:56:00  94.3  32.061230  34.784594  273
82    23013  09:58:00  95.2  32.055636  34.780466  157

[83 rows x 6 columns]

In [51]:
ConvertToOrig(count)

2:40

In [6]:
from datetime import datetime

now = datetime.now()

print("Current Time =", now)

Current Time = 2021-01-14 13:42:04.017315

In [6]:
#Demo waze information

import WazeRouteCalculator
import logging


logger = logging.getLogger('WazeRouteCalculator.WazeRouteCalculator')
logger.setLevel(logging.DEBUG)
handler = logging.StreamHandler()
logger.addHandler(handler)

from_address = '32.704075,34.96925'
to_address = '32.676436,34.96162'
region = 'IL'
route = WazeRouteCalculator.WazeRouteCalculator(from_address, to_address, region)
time = route.calc_route_info()

From: 32.704075,34.96925 - to: 32.676436,34.96162
From: 32.704075,34.96925 - to: 32.676436,34.96162
From: 32.704075,34.96925 - to: 32.676436,34.96162
From: 32.704075,34.96925 - to: 32.676436,34.96162
Start coords: (32.704075, 34.96925)
Start coords: (32.704075, 34.96925)
Start coords: (32.704075, 34.96925)
Start coords: (32.704075, 34.96925)
End coords: (32.676436, 34.96162)
End coords: (32.676436, 34.96162)
End coords: (32.676436, 34.96162)
End coords: (32.676436, 34.96162)
Time 2.33 minutes, distance 3.17 km.
Time 2.33 minutes, distance 3.17 km.
Time 2.33 minutes, distance 3.17 km.
Time 2.33 minutes, distance 3.17 km.

#Another Libs which help us to find information between two locations points