# KNN project 
## Oleg and Yali

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
df = pd.read_excel('output_030421_1700_4sec.xls')
df

,Unnamed: 0,Station,Time,Dist,Lat,Lon,i0,i1,i2,i3,...,i15,i16,i17,i18,i19,i20,i21,i22,i23,i24
0,0,42658,07:00:00,0.0,32.793372,34.958985,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,42362,07:02:00,1.3,32.789609,34.962117,154,130,127,136,...,124,139,140,130,107,127,133,123,123,136
2,2,40964,07:03:00,1.9,32.784590,34.962626,356,246,233,204,...,181,196,192,186,173,178,189,183,183,193
3,3,40958,07:04:00,2.2,32.781207,34.962876,492,337,289,238,...,211,226,222,214,203,208,218,212,213,222
4,4,40897,07:06:00,3.2,32.772031,34.962995,957,703,592,461,...,340,353,356,337,333,340,348,343,343,342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,78,23034,09:49:00,90.7,32.083677,34.806421,10788,10474,10322,10024,...,8757,8921,9124,9003,8844,8855,8913,8925,8908,8745
79,79,21705,09:51:00,91.9,32.079838,34.794882,11248,10903,10706,10413,...,9080,9217,9423,9277,9168,9141,9187,9196,9157,9035
80,80,21472,09:53:00,92.6,32.074914,34.790734,11398,11314,11281,10779,...,9184,9340,9659,9515,9293,9269,9287,9302,9265,9133
81,81,28660,09:56:00,94.3,32.061230,34.784594,11842,11611,11590,11080,...,9453,9584,9958,9837,9612,9567,9541,9539,9531,9370
82,82,23013,09:58:00,95.2,32.055636,34.780466,12068,11804,11804,11307,...,9604,9758,10122,10033,9818,9754,9719,9707,9690,9556

In [3]:
df.describe

<bound method NDFrame.describe of     Unnamed: 0  Station      Time  Dist        Lat        Lon     i0     i1  \
0            0    42658  07:00:00   0.0  32.793372  34.958985      0      0
1            1    42362  07:02:00   1.3  32.789609  34.962117    154    130
2            2    40964  07:03:00   1.9  32.784590  34.962626    356    246
3            3    40958  07:04:00   2.2  32.781207  34.962876    492    337
4            4    40897  07:06:00   3.2  32.772031  34.962995    957    703
..         ...      ...       ...   ...        ...        ...    ...    ...
78          78    23034  09:49:00  90.7  32.083677  34.806421  10788  10474
79          79    21705  09:51:00  91.9  32.079838  34.794882  11248  10903
80          80    21472  09:53:00  92.6  32.074914  34.790734  11398  11314
81          81    28660  09:56:00  94.3  32.061230  34.784594  11842  11611
82          82    23013  09:58:00  95.2  32.055636  34.780466  12068  11804

       i2     i3  ...   i15   i16    i17    i18   i19   i20   i21   i22   i23  \
0       0      0  ...     0     0      0      0     0     0     0     0     0
1     127    136  ...   124   139    140    130   107   127   133   123   123
2     233    204  ...   181   196    192    186   173   178   189   183   183
3     289    238  ...   211   226    222    214   203   208   218   212   213
4     592    461  ...   340   353    356    337   333   340   348   343   343
..    ...    ...  ...   ...   ...    ...    ...   ...   ...   ...   ...   ...
78  10322  10024  ...  8757  8921   9124   9003  8844  8855  8913  8925  8908
79  10706  10413  ...  9080  9217   9423   9277  9168  9141  9187  9196  9157
80  11281  10779  ...  9184  9340   9659   9515  9293  9269  9287  9302  9265
81  11590  11080  ...  9453  9584   9958   9837  9612  9567  9541  9539  9531
82  11804  11307  ...  9604  9758  10122  10033  9818  9754  9719  9707  9690

     i24
0      0
1    136
2    193
3    222
4    342
..   ...
78  8745
79  9035
80  9133
81  9370
82  9556

[83 rows x 31 columns]>

In [4]:
df.corr()

,Unnamed: 0,Station,Dist,Lat,Lon,i0,i1,i2,i3,i4,...,i15,i16,i17,i18,i19,i20,i21,i22,i23,i24
Unnamed: 0,1.000000,-0.713984,0.998151,-0.996888,-0.913824,0.977987,0.977656,0.975721,0.979860,0.981994,...,0.982381,0.981085,0.977701,0.981135,0.982204,0.983011,0.981183,0.983857,0.984901,0.985548
Station,-0.713984,1.000000,-0.710107,0.682710,0.788975,-0.772960,-0.774425,-0.777065,-0.770395,-0.769078,...,-0.758282,-0.763124,-0.769539,-0.765579,-0.764718,-0.766815,-0.768909,-0.761486,-0.763936,-0.763507
Dist,0.998151,-0.710107,1.000000,-0.997822,-0.916930,0.981475,0.981228,0.979455,0.983748,0.985548,...,0.987316,0.985855,0.982645,0.985625,0.986588,0.986946,0.985482,0.988234,0.988647,0.989058
Lat,-0.996888,0.682710,-0.997822,1.000000,0.892595,-0.967424,-0.967073,-0.964711,-0.970427,-0.972891,...,-0.975322,-0.973058,-0.968752,-0.972850,-0.974267,-0.974714,-0.972616,-0.976808,-0.977299,-0.977870
Lon,-0.913824,0.788975,-0.916930,0.892595,1.000000,-0.955438,-0.956067,-0.958244,-0.954070,-0.951912,...,-0.948966,-0.953557,-0.955803,-0.953347,-0.951578,-0.952464,-0.953613,-0.946899,-0.948559,-0.948494
i0,0.977987,-0.772960,0.981475,-0.967424,-0.955438,1.000000,0.999887,0.999683,0.999580,0.999255,...,0.998152,0.998691,0.999049,0.998804,0.998613,0.998622,0.998836,0.997806,0.998024,0.997919
i1,0.977656,-0.774425,0.981228,-0.967073,-0.956067,0.999887,1.000000,0.999904,0.999793,0.999481,...,0.998382,0.998871,0.999317,0.999087,0.998894,0.998899,0.999076,0.998106,0.998299,0.998193
i2,0.975721,-0.777065,0.979455,-0.964711,-0.958244,0.999683,0.999904,1.000000,0.999650,0.999174,...,0.997965,0.998564,0.999239,0.998862,0.998593,0.998582,0.998806,0.997646,0.997825,0.997686
i3,0.979860,-0.770395,0.983748,-0.970427,-0.954070,0.999580,0.999793,0.999650,1.000000,0.999808,...,0.999091,0.999323,0.999567,0.999573,0.999495,0.999501,0.999550,0.999021,0.999082,0.998956
i4,0.981994,-0.769078,0.985548,-0.972891,-0.951912,0.999255,0.999481,0.999174,0.999808,1.000000,...,0.999392,0.999511,0.999489,0.999737,0.999753,0.999806,0.999779,0.999433,0.999600,0.999557
i5,0.979603,-0.772292,0.983469,-0.970216,-0.952639,0.998737,0.999153,0.998984,0.999551,0.999755,...,0.999188,0.999263,0.999457,0.999618,0.999630,0.999665,0.999693,0.999363,0.999417,0.999321
i6,0.982707,-0.768823,0.986188,-0.973944,-0.950576,0.998370,0.998739,0.998391,0.999304,0.999754,...,0.999377,0.999309,0.999161,0.999620,0.999734,0.999814,0.999700,0.999624,0.999803,0.999773
i7,0.980967,-0.769400,0.984968,-0.972106,-0.953086,0.998727,0.999070,0.998828,0.999527,0.999788,...,0.999516,0.999609,0.999601,0.999838,0.999842,0.999859,0.999878,0.999541,0.999674,0.999595
i8,0.980275,-0.769809,0.984555,-0.971590,-0.951867,0.998688,0.999054,0.998823,0.999528,0.999783,...,0.999568,0.999629,0.999671,0.999851,0.999863,0.999835,0.999882,0.999597,0.999636,0.999541
i9,0.981459,-0.768772,0.985527,-0.972829,-0.952350,0.998789,0.999111,0.998853,0.999605,0.999865,...,0.999622,0.999700,0.999658,0.999905,0.999934,0.999936,0.999928,0.999655,0.999740,0.999672
i10,0.979588,-0.766470,0.984403,-0.971130,-0.953839,0.998941,0.999181,0.998980,0.999582,0.999641,...,0.999735,0.999904,0.999908,0.999925,0.999835,0.999713,0.999865,0.999357,0.999334,0.999225
i11,0.983934,-0.760814,0.988208,-0.976427,-0.950741,0.998350,0.998584,0.998198,0.999310,0.999607,...,0.999867,0.999756,0.999350,0.999821,0.999894,0.999864,0.999744,0.999728,0.999774,0.999744
i12,0.986474,-0.753010,0.990602,-0.980008,-0.946373,0.997343,0.997553,0.996972,0.998504,0.999027,...,0.999648,0.999234,0.998436,0.999260,0.999442,0.999389,0.999085,0.999467,0.999542,0.999600
i13,0.989989,-0.746662,0.993402,-0.984423,-0.941146,0.995559,0.995751,0.994919,0.997001,0.997882,...,0.998654,0.997930,0.996659,0.997989,0.998358,0.998408,0.997832,0.998741,0.998928,0.999092
i14,0.987960,-0.748719,0.992054,-0.982498,-0.940360,0.996034,0.996243,0.995443,0.997431,0.998246,...,0.999165,0.998423,0.997319,0.998436,0.998768,0.998706,0.998297,0.999140,0.999182,0.999270
i15,0.982381,-0.758282,0.987316,-0.975322,-0.948966,0.998152,0.998382,0.997965,0.999091,0.999392,...,1.000000,0.999803,0.999401,0.999763,0.999817,0.999640,0.999628,0.999627,0.999565,0.999505
i16,0.981085,-0.763124,0.985855,-0.973058,-0.953557,0.998691,0.998871,0.998564,0.999323,0.999511,...,0.999803,1.000000,0.999767,0.999893,0.999816,0.999706,0.999818,0.999347,0.999389,0.999334
i17,0.977701,-0.769539,0.982645,-0.968752,-0.955803,0.999049,0.999317,0.999239,0.999567,0.999489,...,0.999401,0.999767,1.000000,0.999812,0.999637,0.999499,0.999744,0.998982,0.998968,0.998822
i18,0.981135,-0.765579,0.985625,-0.972850,-0.953347,0.998804,0.999087,0.998862,0.999573,0.999737,...,0.999763,0.999893,0.999812,1.000000,0.999953,0.999875,0.999911,0.999528,0.999595,0.999522
i19,0.982204,-0.764718,0.986588,-0.974267,-0.951578,0.998613,0.998894,0.998593,0.999495,0.999753,...,0.999817,0.999816,0.999637,0.999953,1.000000,0.999938,0.999900,0.999734,0.999791,0.999724
i20,0.983011,-0.766815,0.986946,-0.974714,-0.952464,0.998622,0.998899,0.998582,0.999501,0.999806,...,0.999640,0.999706,0.999499,0.999875,0.999938,1.000000,0.999918,0.999736,0.999858,0.999813
i21,0.981183,-0.768909,0.985482,-0.972616,-0.953613,0.998836,0.999076,0.998806,0.999550,0.999779,...,0.999628,0.999818,0.999744,0.999911,0.999900,0.999918,1.000000,0.999592,0.999662,0.999576
i22,0.983857,-0.761486,0.988234,-0.976808,-0.946899,0.997806,0.998106,0.997646,0.999021,0.999433,...,0.999627,0.999347,0.998982,0.999528,0.999734,0.999736,0.999592,1.000000,0.999855,0.999745
i23,0.984901,-0.763936,0.988647,-0.977299,-0.948559,0.998024,0.998299,0.997825,0.999082,0.999600,...,0.999565,0.999389,0.998968,0.999595,0.999791,0.999858,0.999662,0.999855,1.000000,0.999967
i24,0.985548,-0.763507,0.989058,-0.977870,-0.948494,0.997919,0.998193,0.997686,0.998956,0.999557,...,0.999505,0.999334,0.998822,0.999522,0.999724,0.999813,0.999576,0.999745,0.999967,1.000000

In [9]:
df

,Unnamed: 0,Station,Time,Dist,Lat,Lon,i0,i1,i2,i3,...,i15,i16,i17,i18,i19,i20,i21,i22,i23,i24
0,0,42658,07:00:00,0.0,32.793372,34.958985,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,42362,07:02:00,1.3,32.789609,34.962117,154,130,127,136,...,124,139,140,130,107,127,133,123,123,136
2,2,40964,07:03:00,1.9,32.784590,34.962626,356,246,233,204,...,181,196,192,186,173,178,189,183,183,193
3,3,40958,07:04:00,2.2,32.781207,34.962876,492,337,289,238,...,211,226,222,214,203,208,218,212,213,222
4,4,40897,07:06:00,3.2,32.772031,34.962995,957,703,592,461,...,340,353,356,337,333,340,348,343,343,342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,78,23034,09:49:00,90.7,32.083677,34.806421,10788,10474,10322,10024,...,8757,8921,9124,9003,8844,8855,8913,8925,8908,8745
79,79,21705,09:51:00,91.9,32.079838,34.794882,11248,10903,10706,10413,...,9080,9217,9423,9277,9168,9141,9187,9196,9157,9035
80,80,21472,09:53:00,92.6,32.074914,34.790734,11398,11314,11281,10779,...,9184,9340,9659,9515,9293,9269,9287,9302,9265,9133
81,81,28660,09:56:00,94.3,32.061230,34.784594,11842,11611,11590,11080,...,9453,9584,9958,9837,9612,9567,9541,9539,9531,9370
82,82,23013,09:58:00,95.2,32.055636,34.780466,12068,11804,11804,11307,...,9604,9758,10122,10033,9818,9754,9719,9707,9690,9556

# EDA

Since this data is artificial, we'll just do a large pairplot with seaborn.

**3. Use seaborn on the dataframe to create a pairplot with the hue indicated by the TARGET CLASS column.**

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
scaler = StandardScaler()

In [10]:
features = df.drop(['Lat','Lon', 'Unnamed: 0', 'Time'], axis=1)
scaler.fit(features)

StandardScaler()

In [11]:
scaled_features = scaler.transform(features)

In [13]:
features

,Station,Dist,i0,i1,i2,i3,i4,i5,i6,i7,...,i15,i16,i17,i18,i19,i20,i21,i22,i23,i24
0,42658,0.0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,42362,1.3,154,130,127,136,145,131,141,141,...,124,139,140,130,107,127,133,123,123,136
2,40964,1.9,356,246,233,204,208,192,204,208,...,181,196,192,186,173,178,189,183,183,193
3,40958,2.2,492,337,289,238,238,222,234,239,...,211,226,222,214,203,208,218,212,213,222
4,40897,3.2,957,703,592,461,391,368,371,386,...,340,353,356,337,333,340,348,343,343,342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,23034,90.7,10788,10474,10322,10024,9900,9899,9528,9708,...,8757,8921,9124,9003,8844,8855,8913,8925,8908,8745
79,21705,91.9,11248,10903,10706,10413,10279,10303,9892,10007,...,9080,9217,9423,9277,9168,9141,9187,9196,9157,9035
80,21472,92.6,11398,11314,11281,10779,10481,10495,10044,10260,...,9184,9340,9659,9515,9293,9269,9287,9302,9265,9133
81,28660,94.3,11842,11611,11590,11080,10831,10876,10335,10516,...,9453,9584,9958,9837,9612,9567,9541,9539,9531,9370
82,23013,95.2,12068,11804,11804,11307,10978,11058,10522,10720,...,9604,9758,10122,10033,9818,9754,9719,9707,9690,9556

# Train Test Split

**9. Use train_test_split to split your data into a training set and a testing set.**

In [12]:
from sklearn.model_selection import train_test_split

In [16]:
test= df.iloc[:,6:]
test

,i0,i1,i2,i3,i4,i5,i6,i7,i8,i9,...,i15,i16,i17,i18,i19,i20,i21,i22,i23,i24
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,154,130,127,136,145,131,141,141,152,131,...,124,139,140,130,107,127,133,123,123,136
2,356,246,233,204,208,192,204,208,211,188,...,181,196,192,186,173,178,189,183,183,193
3,492,337,289,238,238,222,234,239,241,219,...,211,226,222,214,203,208,218,212,213,222
4,957,703,592,461,391,368,371,386,378,359,...,340,353,356,337,333,340,348,343,343,342
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,10788,10474,10322,10024,9900,9899,9528,9708,9726,9343,...,8757,8921,9124,9003,8844,8855,8913,8925,8908,8745
79,11248,10903,10706,10413,10279,10303,9892,10007,10047,9677,...,9080,9217,9423,9277,9168,9141,9187,9196,9157,9035
80,11398,11314,11281,10779,10481,10495,10044,10260,10249,9822,...,9184,9340,9659,9515,9293,9269,9287,9302,9265,9133
81,11842,11611,11590,11080,10831,10876,10335,10516,10549,10166,...,9453,9584,9958,9837,9612,9567,9541,9539,9531,9370
82,12068,11804,11804,11307,10978,11058,10522,10720,10739,10323,...,9604,9758,10122,10033,9818,9754,9719,9707,9690,9556

In [23]:
X = features
y = test

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

# Using KNN

**Import KNeighborsClassifier from scikit learn.**

In [24]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
knn = KNeighborsClassifier(n_neighbors = 58)

In [29]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=58)

In [31]:
pred = knn.predict(X_test)

In [32]:
pred

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0]])